package main

import (
	"flag"

	"github.com/hdevillers/go-gesyntek/heatmap"
)

func main() {
	input := flag.String("input", "", "Input distant data file (generated by GeSynteK).")
	output := flag.String("output", "GeSynteK_Heatmap.pdf", "Output file name (PDF).")
	numDivisions := flag.Int("num-division", 24, "Number of divisions.")
	xLabOffset := flag.Int("x-lab-offset", 3, "Offset (in characters) of labels of X axis.")
	yLabOffset := flag.Int("y-lab-offset", 1, "Offset (in characters) of labels of Y axis.")
	figureWidth := flag.Float64("figure-width", 8.0, "Figure width (inches).")
	figureHeight := flag.Float64("figure-height", 8.0, "Figure height (inches).")
	margin := flag.Float64("margin", 0.2, "Figure margin (inches).")
	title := flag.String("title", "Heatmap of up/downstream kmer distances", "Title of the figure.")
	titleSize := flag.Float64("title-size", 0.3, "Title size (inches).")
	flag.Parse()

	if *input == "" {
		panic("You must provide an input distance file.")
	}

	// Create a new heatmap object
	hmd := heatmap.NewHeatMapDistance(
		*numDivisions,
		*xLabOffset,
		*yLabOffset,
		*margin,
		*title,
		*titleSize,
		*figureWidth,
		*figureHeight,
		*output,
	)

	// Load the data
	err := hmd.LoadDistanceFile(*input)
	if err != nil {
		panic(err)
	}

	// Plot
	err = hmd.Plot()
	if err != nil {
		panic(err)
	}
}
